name: MMLeader
main: com.gmail.bobason01.MMLeader
version: 2.0
api-version: 1.16
author: crston
description: MythicMobs kill order statistics with PlaceholderAPI
depend:
  - MythicMobs

softdepend:
  - PlaceholderAPI
  - Parties
  - MMOCore
  - MythicDungeons
  - LuckPerms